sonar.sources=api_gateway,auth_service,role_service
sonar.tests=api_gateway/tests,auth_service/tests,role_service/tests


sonar.issue.ignore.paths=e1
sonar.issue.ignore.paths.e1.rule=security:S2115,security:S2068,python:S2068
sonar.issue.ignore.paths.e1.block=**/tests/**