"""cambiar_role_a_role_id

Revision ID: 0c2fee775deb
Revises: 001
Create Date: 2026-06-26 23:18:10.023307

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0c2fee775deb"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role_id", sa.String(length=36), nullable=False))
    op.create_foreign_key(None, "users", "roles", ["role_id"], ["id"], ondelete="RESTRICT")
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.VARCHAR(length=50),
            server_default=sa.text("'EMPLEADO'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###
